# Generated by Django 5.0.6 on 2024-06-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
