# Generated by Django 5.0.6 on 2024-06-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0006_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='entry',
            name='people_links',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
